lesson5. class NotificationMessage works
js-tasks-ru/js-20230117_info91 pull request #6
Opened 2023-02-01 09:42 UTC by consultapp

2023-02-01 09:43 UTC, jsru commented
Добавляю преподавателя (@dosandk) для код-ревью.

2023-02-01 09:48 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-02-02 15:10 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-02-02 15:43 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @dosandk

2023-02-03 09:51 UTC, dosandk commented on 05-dom-document-loading/1-notification/index.js
> +  static removePrev = false;
👍 good 
лайк за статическое св-во, но вот имя не самое удачное
помните что св-ва это существительные

2023-02-03 09:51 UTC, dosandk commented on 05-dom-document-loading/1-notification/index.js
> +  show(div = document.body) {
👍 good 
лайк за значение по умолчанию

2023-02-03 09:52 UTC, dosandk commented on 05-dom-document-loading/1-notification/index.js
> +    protoLink.removePrev = this.remove.bind(this);
здесь нет необходимости использовать `bind`

2023-02-03 09:52 UTC, dosandk commented on 05-dom-document-loading/1-notification/index.js
> +    div.appendChild(this.element);
используйте `append`
https://dev.to/ibn_abubakre/append-vs-appendchild-a4m

2023-02-03 09:53 UTC, dosandk commented on 05-dom-document-loading/1-notification/index.js
> +    const protoLink = this.constructor.prototype;
🔴 please don't do this
так нельзя обращаться к статическим св-вам,
используйте `NotificationMessage.removePrev`

2023-02-03 09:53 UTC, dosandk commented on 05-dom-document-loading/2-sortable-table-v1/index.js
> +    this._allowSorting = new Map(
зачем тут `Map`?

2023-02-03 09:54 UTC, dosandk commented on 05-dom-document-loading/2-sortable-table-v1/index.js
> +        .filter((v) => {
не пишите логику в `constructor` - сделайте это в отдельном методе

2023-02-03 09:54 UTC, dosandk commented on 05-dom-document-loading/2-sortable-table-v1/index.js
> +    const tmpQ = this._element.querySelectorAll("div[data-element]");
что такое `tmpQ`?

2023-02-03 09:55 UTC, dosandk commented on 05-dom-document-loading/2-sortable-table-v1/index.js
> +    this._subElements = { head: tmpQ[0], body: tmpQ[1] };
почему бы не сделать это динамически? чтобы не менять код в случае добавления эл-тов

2023-02-03 09:56 UTC, dosandk commented on 05-dom-document-loading/2-sortable-table-v1/index.js
> +          alt="${cell[0].source ?? ""}"
почему используется `??` оператор вместо `||`?

2023-02-03 09:57 UTC, dosandk commented on 05-dom-document-loading/2-sortable-table-v1/index.js
> +    return this._currentSort.orderValue && id === this._currentSort.fieldValue
можно ли упростить такую проверку?
```
this._currentSort.orderValue && id === this._currentSort.fieldValue
```
до 
```
id === this._currentSort.fieldValue
```

2023-02-03 09:57 UTC, dosandk commented on 05-dom-document-loading/2-sortable-table-v1/index.js
> +          default:
а где явная проверка что это `number`?

2023-02-03 09:58 UTC, dosandk requested changes
следует дать ответы на вопросы

2023-02-03 12:04 UTC, jsru commented
Добавляю преподавателя (@dosandk) для код-ревью.

2023-02-03 12:05 UTC, consultapp commented on 05-dom-document-loading/1-notification/index.js
> +    protoLink.removePrev = this.remove.bind(this);
Я не понял почему здесь не нужен bind. Мы вроде привязываем
    текущий контекст экземпляра  к методу, а вызываем из другого экземпляра,
    который про предшественника не знает и через статичное св-во NotificationMessage.

    NotificationMessage.linkToActiveRemove = this.remove.bind(this);

2023-02-03 12:06 UTC, consultapp commented on 05-dom-document-loading/2-sortable-table-v1/index.js
> +    this._allowSorting = new Map(
Map тут хранит коллекцию id => sortType 
по ключу поля потом получается тип сортировки.
Вопрос в том, что можно заменить на Объект или Array?
Или вообще переделать на что-то другое?

2023-02-04 14:40 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-02-04 15:36 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @dosandk

2023-02-04 18:57 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @dosandk

2023-02-06 11:49 UTC, dosandk commented on 05-dom-document-loading/2-sortable-table-v1/index.js
> +    this._allowSorting = new Map(
`Map` следует использовать тогда, когда есть необходимость хранить в ключах что-то отличное от строк или символов, в остальных случаях подойдет обычный объект

2023-02-06 11:51 UTC, dosandk commented on 05-dom-document-loading/1-notification/index.js
> +    const protoLink = this.constructor.prototype;
```js
class NotificationMessage {
  static getName() {
    return "My name is NotificationMessage";
  }

  lognameA() {
    console.log(NotificationMessage.getName());
  }

  lognameB() {
    console.log(this.constructor.getName());
  }
}

class ErrorNotification extends NotificationMessage {
  static getName() {
    return "My name is ErrorNotification";
  }
}

const errorNotification = new ErrorNotification();

errorNotification.lognameA(); // My name is NotificationMessage
errorNotification.lognameB(); // My name is ErrorNotification
```

2023-02-06 11:51 UTC, dosandk commented on 05-dom-document-loading/2-sortable-table-v1/index.js
> +          alt="${cell[0].source ?? ""}"
@consultapp ?

2023-02-06 11:53 UTC, dosandk commented on 05-dom-document-loading/1-notification/index.js
> +  static linkToActiveRemoveRemove = false;
почему данное св-во проинициализировано значением `false`?
разве там будет хранится булевский тип?

2023-02-06 11:54 UTC, dosandk commented on 05-dom-document-loading/1-notification/index.js
> +    NotificationMessage.linkToActiveRemove = this.remove.bind(this);
здесь нужно не биндить метод, а передать ссылку на текущий нотификейшен, вот так:
```js
NotificationMessage.activeNotification = this;
```

2023-02-06 11:55 UTC, dosandk commented on 05-dom-document-loading/2-sortable-table-v1/index.js
> +  _subElements = [];
почему некоторые методы имеет нижнее подчеркивание в имени?

2023-02-06 11:56 UTC, dosandk commented on 05-dom-document-loading/2-sortable-table-v1/index.js
> +    for (const item of this.element.querySelectorAll("div[data-element]")) {
было бы неплохо вынести логику работы с `subElements` в отдельный метод

2023-02-06 11:57 UTC, dosandk commented on 05-dom-document-loading/2-sortable-table-v1/index.js
> +         return headerColumn.template
👍 good

2023-02-06 11:57 UTC, dosandk commented on 05-dom-document-loading/2-sortable-table-v1/index.js
> +          case "number":
👍 good

2023-02-06 11:58 UTC, dosandk commented on 05-dom-document-loading/2-sortable-table-v1/index.js
> +            this._data.sort();
лучше вывести сообщение об ошибке тут

2023-02-06 11:58 UTC, dosandk commented on 06-events-practice/1-sortable-table-v2/index.js
> +    for (const item of this.element.querySelectorAll("div[data-element]")) {
вынесите эту логику в отдельный метод

2023-02-06 11:59 UTC, dosandk commented on 06-events-practice/1-sortable-table-v2/index.js
> +        this.headerConfig.filter((item) => item.id === target.dataset.id)[0]
пожалуйста вынесите логику этого `filter` в отдельную переменную, а после передайте значение в `if`

2023-02-06 12:00 UTC, dosandk commented on 06-events-practice/1-sortable-table-v2/index.js
> +      this.headerConfig.filter((item) => item.id === sortId)[0].sortType
так тоже не следует делать, вынесите в переменную!

2023-02-06 12:00 UTC, dosandk commented on 06-events-practice/1-sortable-table-v2/index.js
> +                .toUpperCase()
зачем тут `toUpperCase`?

2023-02-06 12:02 UTC, dosandk commented on 06-events-practice/1-sortable-table-v2/index.js
> +    return `    <div data-element="loading" class="loading-line sortable-table__loading-line"></div>`;
пробелы перед `<div` - удалите!

2023-02-06 12:03 UTC, dosandk commented on 06-events-practice/1-sortable-table-v2/index.js
> +      this.render();
🔴 please don't do this
так делать нельзя! нельзя перерендеривать таблицу заново!

2023-02-06 12:06 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-02-06 12:28 UTC, dosandk commented on 06-events-practice/2-tooltip/index.js
> +  static MOUSE_INDENT = 5; // отступ в пикселях от указателя мыши, добавляет плавность и видимость текста
почему данный отступ объявлен через статическое св-во?

2023-02-06 12:29 UTC, dosandk commented on 06-events-practice/2-tooltip/index.js
> +  static render(text, parent = document.body) {
почему все методы сделаны статическими?

2023-02-06 12:30 UTC, dosandk commented on 06-events-practice/2-tooltip/index.js
> +      parent.addEventListener("mousemove", Tooltip.move);
пожалуйста обработчики к-е связаны с перемещение курсора добавляйте глобально на `document`

2023-02-06 12:31 UTC, dosandk commented on 06-events-practice/2-tooltip/index.js
> +      parent.removeEventListener("mousemove", Tooltip.move);
good 👍
лайк за удаление обработчика

2023-02-06 12:31 UTC, dosandk commented on 06-events-practice/2-tooltip/index.js
> +    document.removeEventListener("pointerout", Tooltip.out);
было бы неплохо и `pointermove` удалить, ведь неизвестно когда сработает метод `destroy`

2023-02-06 12:32 UTC, dosandk commented on 06-events-practice/2-tooltip/index.js
> +  static out = (event) => {
`out` не самое лучшее имя для метода
методы - это глаголы!

2023-02-06 12:33 UTC, dosandk commented on 06-events-practice/2-tooltip/index.js
> +    return Tooltip;
Singleton может выглядеть вот так:
```constructor() {
    if (Tooltip.instance) {
      return Tooltip.instance;
    }

    Tooltip.instance = this;
  }js

```

2023-02-06 12:35 UTC, dosandk commented on 06-events-practice/1-sortable-table-v2/index.js
> +    this.subElements.header.addEventListener("pointerdown", (event) => {
good 👍 лайк за применение "event delegation"

2023-02-06 12:36 UTC, dosandk commented on 06-events-practice/1-sortable-table-v2/index.js
> +      const target = event.target.closest("div");
🔴 please don't do this
здесь следует искать эл-т по дата-атрибуту - "sortable"

2023-02-06 12:37 UTC, dosandk requested changes
пожалуйста посмотрите комментарии, дайте ответы на вопросы, внесите изменения.
Поправьте реализацию Tooltip - не должны быть все методы статическими

2023-02-06 13:20 UTC, jsru commented
Добавляю преподавателя (@dosandk) для код-ревью.

2023-02-06 13:40 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-02-06 13:45 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-02-06 13:55 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-02-06 13:56 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @dosandk

2023-02-06 14:37 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @dosandk

2023-02-06 15:40 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @dosandk

2023-02-06 15:57 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @dosandk

2023-02-07 14:02 UTC, dosandk commented on 06-events-practice/3-double-slider/index.js
> +  static MAX_PERCENT = 100;
почему данные св-ва статические?

2023-02-07 14:03 UTC, dosandk commented on 06-events-practice/3-double-slider/index.js
> +    this.step = step > 0 ? step : 0;
может лучше:
```
this.step = step || 0;
```

2023-02-07 14:06 UTC, dosandk approved these changes
👍 good 
лайк за реализацию DoubleSlider
но посмотрите коменты к предыдущим компонентам

2023-02-07 14:07 UTC, merged